name: Build container image and deploy on dockerhub
on:
  push:
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruby-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2.4.0
      - run: ruby -c *.rb
  test-IEEE-IoT:
    runs-on: ubuntu-latest
    if: github.repository == 'DanySK/auto-latexdiff' && github.event_name == 'push'
    steps:
      - name: Compute test version
        id: trick
        shell: bash
        run: |
          # Idea: the regex matcher of Renovate keeps this string up to date automatically
          # The version is extracted and used to access the correct version of the scripts
          USES=$(cat <<TRICK_RENOVATE
          - uses: DanySK/Paper-2021-AppliedSoftComputing-Pulverization@4bb3998f6d90124d81348c7f96e0d1b5d5c29854
          TRICK_RENOVATE
          )
          echo "Scripts update line: \"$USES\""
          echo "Computed version: \"${USES#*@}\""
          echo "::set-output name=version::${USES#*@}"
      - name: Checkout test
        uses: actions/checkout@v2.4.0
        with:
          repository: DanySK/Paper-2021-AppliedSoftComputing-Pulverization
          ref: ${{ steps.trick.outputs.version }}
          path: test
          fetch-depth: 0
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout action
        uses: actions/checkout@v2.4.0
        with:
          path: action
      - name: Test
        uses: ./action/
        id: run
        with:
          directory: test
          fail-on-error: true
          files: paper*-ieee-iot-*.tex
          tags: |
            3\.0\.0
      - name: Verify that the diff has been produced
        shell: bash
        run: |
          [ -s test/paper*-ieee-iot-*-wrt-3.0.0.tex ]
      - name: Debug prints
        shell: bash
        if: failure()
        run: |
          ls -ahl test
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@0.3.69
      - name: Verify that the diff has been compiled
        shell: bash
        run: |
          [ -s test/paper*-ieee-iot-*-wrt-3.0.0.pdf ]
  test-TAAS-smartcam:
    runs-on: ubuntu-latest
    if: github.repository == 'DanySK/auto-latexdiff' && github.event_name == 'push'
    steps:
      - name: Compute test version
        id: trick
        shell: bash
        run: |
          USES=$(cat <<TRICK_RENOVATE
          - uses: DanySK/Paper-2019-PMC-SmartCam@7b1972e2890e8cbc7dc970f75fe44c9cbc028395
          TRICK_RENOVATE
          )
          echo "Scripts update line: \"$USES\""
          echo "Computed version: \"${USES#*@}\""
          echo "::set-output name=version::${USES#*@}"
      - name: Checkout test
        uses: actions/checkout@v2.4.0
        with:
          repository: DanySK/Paper-2019-PMC-SmartCam
          ref: ${{ steps.trick.outputs.version }}
          path: test
          fetch-depth: 0
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout action
        uses: actions/checkout@v2.4.0
        with:
          path: action
      - name: Test
        uses: ./action/
        id: run
        with:
          directory: test
          fail-on-error: true
          files: |
            *paper*taas*.tex
          tags: |
            3\.1\.0
      - name: Verify that the diff has been produced
        shell: bash
        run: |
          [ -s test/*paper*taas*-wrt-3.1.0.tex ]
      - name: Debug prints
        shell: bash
        if: failure()
        run: |
          ls -ahl test
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@0.3.69
      - name: Verify that the diff has been compiled
        shell: bash
        run: |
          [ -s test/*paper*taas*-wrt-3.1.0.pdf ]
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - ruby-syntax
      - test-IEEE-IoT
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Semantic Release
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: npx semantic-release
