name: Build container image and deploy on dockerhub
on:
  push:
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruby-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: ruby -c *.rb
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
        has-secrets: ${{ steps.secrets.outputs.has-secrets }}
    steps:
        - name: Find if secrets are available
          uses: DanySK/are-secrets-available@1.0.0
          id: secrets
          with:
            secrets: ${{ toJson(secrets) }}
  tests:
    needs:
      - check-secrets
    runs-on: ubuntu-latest
    if:  github.repository == 'DanySK/auto-latexdiff' && needs.check-secrets.outputs.has-secrets
    steps:
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'latexdiff.rb') }}
      - name: Compute test version
        id: trick
        shell: bash
        run: |
          # Idea: the regex matcher of Renovate keeps this string up to date automatically
          # The version is extracted and used to access the correct version of the scripts
          IEEE=$(cat <<TRICK_RENOVATE
          - uses: DanySK/Paper-2021-AppliedSoftComputing-Pulverization@d468414752d7ac5ace484de48232e33e47af29d5
          TRICK_RENOVATE
          )
          TAAS=$(cat <<TRICK_RENOVATE
          - uses: DanySK/Paper-2019-PMC-SmartCam@c49d1e0b1d12fc42992bf4aaf7cec5f58bdd3949
          TRICK_RENOVATE
          )

          echo "IEEE update line: \"$IEEE\""
          echo "TAAS update line: \"$TAAS\""
          echo "Computed version for IEEE: \"${IEEE#*@}\""
          echo "Computed version for TAAS: \"${TAAS#*@}\""
          echo "::set-output name=ieee-version::${IEEE#*@}"
          echo "::set-output name=taas-version::${TAAS#*@}"
      - name: Checkout test
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: DanySK/Paper-2021-AppliedSoftComputing-Pulverization
          ref: ${{ steps.trick.outputs.ieee-version }}
          path: ieee
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout test
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: DanySK/Paper-2019-PMC-SmartCam
          ref: ${{ steps.trick.outputs.taas-version }}
          path: taas
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout action
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: action
      - name: Compute diff on IEEE
        uses: ./action/
        with:
          directory: ieee
          fail-on-error: true
          files: paper*-ieee-iot-*.tex
          tags: |
            3\.0\.0
      - name: Compute diff on TAAS
        uses: ./action/
        with:
          directory: taas
          fail-on-error: true
          files: |
            *paper*taas*.tex
          tags: |
            3\.1\.0
      - name: Verify that the diffs have been produced
        shell: bash
        run: |
          [ -s ieee/paper*-ieee-iot-*-wrt-3.0.0.tex ]
          [ -s taas/*paper*taas*-wrt-3.1.0.tex ]
      - name: Debug prints
        shell: bash
        if: failure()
        run: |
          ls -ahl ieee
          ls -ahl taas
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@0.4.8
      - name: Verify that the diffs have been compiled
        shell: bash
        run: |
          [ -s ieee/paper*-ieee-iot-*-wrt-3.0.0.pdf ] || (cat ieee/paper*-ieee-iot-*-wrt-3.0.0.tex; exit 1)
          [ -s taas/*paper*taas*-wrt-3.1.0.pdf ] || (cat taas/*paper*taas*-wrt-3.1.0.tex; exit 1)
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'latexdiff.rb') }}
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build the container
        run: docker build -t danysk/auto-latexdiff .
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - build-container
      - ruby-syntax
      - tests
    steps:
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'latexdiff.rb') }}
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Find if secrets are available
        uses: DanySK/are-secrets-available@1.0.0
        id: secrets
        with:
          secrets: ${{ toJson(secrets) }}
      - name: Install Semantic Release
        run: npm install
      - name: Login to Docker Hub
        if: steps.secrets.outputs.has-secrets
        uses: docker/login-action@v3.0.0
        with:
          username: danysk
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: npx semantic-release
  success:
    runs-on: ubuntu-22.04
    needs:
      - build-container
      - release
      - ruby-syntax
      - tests
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
